# Server
server.port=8080

# Application
spring.application.name=voltx

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/voltx
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
